---
title: "SOOS plan builder"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r}
library(flexdashboard)
library(leaflet)
library(dplyr)
fname <- normalizePath("filecfc44542018.sqlite")
random_id <- function() {
  paste(sample(c(letters,LETTERS, 0:9), 6, replace = TRUE), collapse = "")
}
epoch <- ISOdate(1970, 1, 1)
```

```{r setup, include = FALSE, eval = TRUE}
library(flexdashboard)
library(leaflet)
library(dplyr)
if (!file.exists(fname)) {
db <- src_sqlite(fname, create = TRUE)
dummytab <- data_frame(ID = "0", name = "dummy", lead = "dummy", 
                       date_start = Sys.Date(), date_end = Sys.Date(), team_size = 0L,
                       llbox = "", 
                       show = FALSE)
d <- data.frame(x = rnorm(1), y = sample(letters, 1))
tab <- copy_to(db, dummytab, temporary = FALSE )
db_insert_into( con = db$con, table = "d", values = d)
db_insert_into( con = db$con, table = "dummytab", values = as.data.frame(dummytab))
#tab <- tbl(db, "d")
}
```

Column {.sidebar}
========================================================================

Enter initial details on  plan. 

```{r}
textInput("project_name", label = "Name of project", value = "A project name")
textInput("lead_name", label = "Leader name", value = "Project leader name")
dateRangeInput("date_range", label = "Date start and end", start = NULL, end = Sys.Date() + 7L)
numericInput("n_team", label = "Number of team members", value = 1L, min = 1L, max = NA_integer_)
actionButton("write", "Write it")
```

Input details
========================================================================

### A map

```{r}
  output$map <- renderLeaflet({
leaflet() %>% addTiles() %>% 
       setView(lng = 147, lat = -44, zoom = 4)
  })
leafletOutput("map", width="100%", height="100%")
```

### Plan details

```{r}
get_data <- function() {  
  db <- src_sqlite(fname, create = FALSE)
  tab <- tbl(db, "dummytab") %>% filter(show > 0) %>% select(-show) %>% distinct() %>% collect()
  rm(db)
  #tab$date_start <- fdate(tab$date_start )
  #tab$date_end <- fdate(tab$date_end)
  tab
}

store_data <- function(innew) {
  db <- src_sqlite(fname, create = FALSE)
  #dummytab <- data_frame(name = "dummy", date_start = Sys.Date(), date_end = Sys.Date(), team_size = 1L, show = TRUE)
  db_insert_into( con = db$con, table = "dummytab", values = as.data.frame(innew))
  rm(db)
}

cdate <- function(x) {
  as.numeric(x) + as.POSIXct("1970-01-01")
}
fdate <- function(x) format(x, "%Y,%B")
formatLoc <- function(lon, lat) {
  sprintf("%s,%s %s,%s", 
                                 format(lon[1], digits = 5), 
                                 format(lon[2], digits = 5), 
                                 format(lat[1], digits = 4), 
                                 format(lat[2], digits = 4)
          )
}
observeEvent(input$write, {
    bounds <- input$map_bounds
     latRng <- range(bounds$north, bounds$south)
     lngRng <- range(bounds$east, bounds$west)
 d <- data_frame(ID = random_id(), name = input$project_name, 
                 lead = input$lead_name, 
                  date_start = cdate(input$date_range[1]), 
                  date_end = cdate(input$date_range[2]), 
                  team_size = input$n_team, 
                 llbox = formatLoc(lngRng, latRng), show = TRUE)
  store_data(d)
  
  
})

DT::renderDataTable({
  input$write
    get_data()
})

```

Internals (debug)
========================================================================

```{r}
shiny::renderText(sprintf("Delete this file manually to clear the DB\n%s", fname))

```

