---
title: "SOOS Project Plan"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(tibble)
```


     
---------------------------------------------

### Voyage

```{r}
nam1 <- c("Vehicle_Type", "Vehicle_Name",  "Nation", "Voyage_Leader_Name", "Voyage_Leader_Email", "Voyage_Description")
nam2 <- c("Tentative_Date", "Essential_Ocean_Variables")
selectInput("Vehicle_Type", label = "Vehicle_Type",
            choices = c("ship", "helicopter", "land vehicle", "convoy", "other"),
            selected = "ship")
textInput("Vehicle_Name", label = "Vehicle_Name", 
            placeholder = "Boaty McBoatFace")
dateRangeInput("Tentative_Date", "Tentative_Date")
textInput("Nation", label = "Nation")
textInput("Voyage_Leader_Name", label = "Voyage_Leader_Name")
textInput("Voyage_Leader_Email", label = "Voyage_Leader_Email")
textInput("Voyage_Description", label = "Voyage_Description")

selectInput("Essential_Ocean_Variables", label = "Essential_Ocean_Variables", 
            choices = c("colour", "flavour", "smell", "style"))

```
