---
title: "SOOS plan builder"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r}
library(flexdashboard)
library(leaflet)
library(dplyr)
fname <- "C:\\Users\\MICHAE~1\\AppData\\Local\\Temp\\RtmpGS5cwG\\filecfc22271009.sqlite"
```

```{r setup, include = FALSE, eval = FALSE}
library(flexdashboard)
library(leaflet)
library(dplyr)
db <- src_sqlite(fname, create = TRUE)
dummytab <- data_frame(name = "dummy", date_start = Sys.Date(), date_end = Sys.Date(), team_size = 0L, show = FALSE)
d <- data.frame(x = rnorm(1), y = sample(letters, 1))
tab <- copy_to(db, dummytab, temporary = FALSE )
db_insert_into( con = db$con, table = "d", values = d)
db_insert_into( con = db$con, table = "dummytab", values = as.data.frame(dummytab))
tab <- tbl(db, "d")
```
Column {.sidebar}
-----------------------------------------------------------------------

Enter initial details on  plan. 

```{r}
textInput("plan_name", label = "Name of  plan", value = "A plan name")
dateRangeInput("date_range", label = "Date start and end", start = NULL, end = Sys.Date() + 7L)
numericInput("n_team", label = "Number of team members", value = 1L, min = 1L, max = NA_integer_)
actionButton("do", "Click Me")
```

Column {}
-----------------------------------------------------------------------

### A map

```{r}
leaflet() %>% addTiles()
```

### Plan details

```{r}
get_data <- function() {  
  db <- src_sqlite(fname, create = FALSE)
 tab <- tbl(db, "dummytab") %>% filter(show > 0) %>% select(-show) %>% distinct() %>% collect()
 rm(db)
 tab
}

store_data <- function(innew) {
  db <- src_sqlite(fname, create = FALSE)
  dummytab <- data_frame(name = "dummy", date_start = Sys.Date(), date_end = Sys.Date(), team_size = 1L, show = TRUE)
  db_insert_into( con = db$con, table = "dummytab", values = as.data.frame(innew))
   rm(db)
}

 observeEvent(input$do, {
    session$sendCustomMessage(type = 'testmessage',
      message = 'Thank you for clicking')
    d <- data_frame(name = input$plan_name, 
             date_start = as.numeric(input$date_range[1]) + as.Date("1970-01-01"), 
             date_end = as.numeric(input$date_range[2]) +  as.Date("1970-01-01"), 
             team_size = input$n_team, show = TRUE)
 store_data(d)
  
 
  })
 
 DT::renderDataTable({
   input$do
  get_data()
})
```


